zelfstandigenaamwoorden = [
    'kopje',
    'kop',
    'pop',
    'poppen',
    'poppenwagen',
    'jurk',
    'jurkje',
    'nagel',
    'nageltje',
    'neus',
    'neusje',
    'vinger',
    'man',
    'vrouw',
    'moeder',
    'vader',
    'kroon',
    'schort',
    'kraaltje',
    'kraal',
    'kralen',
    'hand',
    'sok',
    'sokken',
    'sokje',
    'sokjes',
    'schoen',
    'schoenen',
    'schoentje',
    'schoentjes',
    'mond',
    'monden',
    'mondje',
    'mondjes',
    'poppenkind',
    'bed',
    'bedje',
    'knop',
    'knopje',
    'touw',
    'touwtje',
    'ballon',
    'voet',
    'voeten',
    'voetje',
    'voetjes',
    'tong',
    'tongetje',
    'haar',
    'rug',
    'arm',
    'baard',
    'vriend',
    'vriendje',
    'vriendjes',
    'neus',
    'stekel',
    'stekeltje',
    'stekeltjes',
    'schotel',
    'schoteltje',
    'poot',
    'pootje',
    'pootjes',
    'staart',
    'hand',
    'tenen',
    'elfjes',
    'hoofd',
    'broek',
    'broekje',
    'rozen',
    'roos',
    'vingers',
    'duim',
    'neusje',
    'handje',
    'munten',
    'bek',
    'ijsje',
    'schouders',
    'mandje',
    'drankje',
    'kop',
    'bekje',
    'zwembroek',
    'nek',
    'rugje',
    'armen',
    'hals',
    'panto', # ffels
    'tabbert',
    'appelbol',
    'laarsjes',
    'mondje',
    'boterham',
    'pols',
]
# Bah,  dat zijn paardebloemen,
# Er zijn meeuwen
# Ze zijn weg hoor.
# overal zijn kralen.

werkwoorden_derde_meervoud = [
    ('knipt', 'knippen'),
    ('valt', 'vallen'),
    ("heeft", "hebben"),
    ("zegt", "zeggen"),
    ("kijkt", "kijken"),
    ("zit", "zitten"),
    ("lacht", "lachen"),
    ("loopt", "lopen"),
    ("maakt", "maken"),
    ("speelt", "spelen"),
    ("gilt", "gillen"),
    # ("is", "zijn"), # Apart
]

werkwoorden = [w for wd in werkwoorden_derde_meervoud for w in wd]


bijwoorden = [
    'zo',
    'op',
    'achterna',
    'in',
]

bijvoegelijkenaamwoorden = [
    'blauw',
    'blauwe',
    'eigen',
    'zijden',
    # 'vies', # gaat mis met zijn
    'lege',
    'kleine',
]

lidwoorden = ['de', 'het', 'een']

interpunctie = ["&#x2018;", "&#x2019;", " ", ".", ",", ":", ";", "!", "?"]
